name: flutter_widget_collection
description: A Flutter package save everything widget favorite.
version: 0.0.1
author: MinhMinh<minhminh9201@gmail.com>
homepage: https://github.com/lqminhlab/flutter_widget_collection

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
